### ISSUE TITLE
Brightness slider not showing black (v1.0.5)

### ISSUE THREAD

**Issue by alfietapping** [skydoves/colorpicker-compose#42]
**Please complete the following information:**
- Library Version [e.g. v1.0.5]
- Affected Device(s) [e.g. Pixel 6 Android 13]
 
**Describe the Bug:**

Brightness slider is white on left side

**Expected Behavior:**

The brightness slider should be black on the left side, instead it's white. 

Here's a screenshot displaying the issue

![Screenshot_20231019-143031](https://github.com/skydoves/colorpicker-compose/assets/52085556/8c3f027b-3eb9-4853-a8aa-a3e181eeec9b)

**Comment by moertel** [comment]
@alfietapping I submitted a PR for this just now. While we wait for the maintainer to take a look at it, you can work around the problem by giving your `BrightnessSlider` a black background. The default `borderRadius` is `6.dp` in the code, so that's what I used here to make it blend in seamlessly. If you override that value, make sure to change it in the `Modifier` too:

```kotlin
BrightnessSlider(
    modifier = Modifier
        .fillMaxWidth()
        .background(color = Color.Black, shape = RoundedCornerShape(6.dp))
        .height(35.dp),
    controller = controller,
)
```

**Comment by alfietapping** [comment]
@moertel thanks for this, much appreciated!

**Comment by skydoves** [comment]
@moertel @alfietapping Thanks for addressing this issue guys! I checked the PR, and it looks great to me. The next version will be released with additional bug fixes.

**Comment by moertel** [comment]
Thanks a lot for the super quick release, @skydoves! I can confirm it's working normally again in 1.0.7 🚀
